/*
jsonpp - JSON for Modern C++
https://github.com/mikami-w/jsonpp

This file is auto-generated by scripts/generate_single_include.py
*/

#ifndef JSONPP_SINGLE_INCLUDE_JSONPP_HPP
#define JSONPP_SINGLE_INCLUDE_JSONPP_HPP

#include <type_traits>
#include <cstddef>
#include <string_view>
#include <functional>
#include <map>
#include <unordered_map>
#include <stdexcept>
#include <string>
#include <vector>
#include <cstdint>
#include <memory>
#include <ostream>
#include <algorithm>
#include <array>
#include <charconv>
#include <variant>
#include <cassert>
#include <istream>

// ---- begin: src/detail/macro_def.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */


#define MAX_NESTING_DEPTH 1024  // Change this value as needed

#define JSONPP_IMPORT_PARSERBASE_MEMBERS_ \
using ParserBase<StreamT>::m_stream;        \
using ParserBase<StreamT>::peek;            \
using ParserBase<StreamT>::advance;         \
using ParserBase<StreamT>::tell_pos;        \
using ParserBase<StreamT>::eof;             \
using ParserBase<StreamT>::consume;         \
using ParserBase<StreamT>::size;            \
using ParserBase<StreamT>::seek;            \
using ParserBase<StreamT>::get_chunk;       \
using ParserBase<StreamT>::read_chunk_until;

#define BASIC_JSON_TEMPLATE \
template <  \
template<typename U, typename V, typename... Args> class ObjectType,    \
template<typename U, typename... Args> class ArrayType, \
typename StringType,    \
typename BooleanType,   \
typename NumberIntegerType, \
typename NumberFloatType,   \
template<typename U> class AllocatorType,   \
typename CustomBaseClass    \
>

#define BASIC_JSON_TYPE \
basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberFloatType, AllocatorType, CustomBaseClass>

#define _STR(x) #x
#define TO_STRING(x) _STR(x)

#define LOG_VAR(x) std::cout << "Variable " << #x << " = " << x << std::endl;

#define JSONPP_CHECK_EOF_(type, start) \
do { \
    if (eof()) \
    throw JsonParseError(("Unexpected end of file while parsing " type ", starting"), start); \
} while(0)

// ---- end: src/detail/macro_def.hpp ----

// ---- begin: src/detail/traits.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



namespace jsonpp::traits
{
    namespace details_t
    {
        template <typename T, typename = void>
        struct is_json_stream_impl: std::false_type {};

        template <typename T>
        struct is_json_stream_impl<T, std::void_t<
            decltype(std::declval<T>().peek()),
            decltype(std::declval<T>().advance()),
            decltype(std::declval<T>().tell_pos()),
            decltype(std::declval<T>().eof())
        >>
        {
        private:
            using peek_return_t = decltype(std::declval<T>().peek());
            using advance_return_t = decltype(std::declval<T>().advance());
            using tell_pos_return_t = decltype(std::declval<T>().tell_pos());
            using eof_return_t = decltype(std::declval<T>().eof());

        public:
            static constexpr bool value = std::conjunction_v<
                std::is_same<peek_return_t, int>,
                std::is_same<advance_return_t, int>,
                std::is_same<tell_pos_return_t, std::size_t>,
                std::is_same<eof_return_t, bool>
            >;
        };

        struct PredicateFunctor
        {
            bool operator()(char const&) const { return false; }
        };

        // trait for std::map
        template <template <typename... Args> class MapT>
        struct is_std_map: std::false_type {};

        template <>
        struct is_std_map<std::map>: std::true_type {};

        template <template <typename... Args> class MapT>
        inline constexpr bool is_std_map_v = is_std_map<MapT>::value;

        // trait for std::unordered_map
        template <template <typename... Args> class MapT>
        struct is_std_unordered_map: std::false_type {};

        template <>
        struct is_std_unordered_map<std::unordered_map>: std::true_type {};

        template <template <typename... Args> class MapT>
        inline constexpr bool is_std_unordered_map_v = is_std_unordered_map<MapT>::value;
    }

    template <typename T>
    struct is_json_stream: details_t::is_json_stream_impl<T> {};

    template <typename T>
    inline constexpr bool is_json_stream_v = is_json_stream<T>::value;

    // Is the stream capable of directly obtaining its complete size
    template <typename T, typename = void>
    struct is_sized_stream: std::false_type {};

    template <typename T>
    struct is_sized_stream<T, std::void_t<decltype(std::declval<T>().size())>>
        : std::true_type {};

    template <typename T>
    inline constexpr bool is_sized_stream_v = is_sized_stream<T>::value;

    // Is the stream a seekable stream (provides seek capability)
    template <typename T, typename = void>
    struct is_seekable_stream: std::false_type {};

    template <typename T>
    struct is_seekable_stream<T,
        std::enable_if_t<is_sized_stream_v<T>,
        std::void_t<
            decltype(std::declval<T>().seek(std::size_t()))
    >>>
        : std::true_type {};

    template <typename T>
    inline constexpr bool is_seekable_stream_v = is_seekable_stream<T>::value;

    // Is the stream a contiguous stream (provides chunk access capability)
    template <typename T, typename = void>
    struct is_contiguous_stream : std::false_type {};

    template <typename T>
    struct is_contiguous_stream<T,
        std::enable_if_t<is_seekable_stream_v<T>,
        std::void_t<
            decltype(std::declval<T>().get_chunk(std::size_t(), std::size_t())),
            decltype(std::declval<T&>().read_chunk_until(std::declval<details_t::PredicateFunctor>()))
    >>>
        : std::true_type {};

    template <typename T>
    inline constexpr bool is_contiguous_stream_v = is_contiguous_stream<T>::value;

    // trait for JSON Serialize Handler
    template <typename T, typename = void>
    struct is_json_serialize_handler : std::false_type {};

    template <typename T>
    struct is_json_serialize_handler<T, std::void_t<
        decltype(std::declval<T>().append(std::declval<char>())),
        decltype(std::declval<T>().append(std::declval<std::string_view>())),
        decltype(std::declval<T>().append(std::declval<char const*>(), std::declval<std::size_t>()))
    >>
        : std::true_type {};

    template <typename T>
    inline constexpr bool is_json_serialize_handler_v = is_json_serialize_handler<T>::value;
}

// ---- end: src/detail/traits.hpp ----

// ---- begin: src/detail/jsonexception.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



namespace jsonpp
{
    /*
     * JSON exceptions
     */
    class JsonException : public std::runtime_error
    {
    public:
        JsonException(std::string const& msg):
            std::runtime_error(msg) {}
    };

    class JsonParseError : public JsonException
    {
    public:
        static constexpr char const* UNPARSABLE_MESSAGE = "Unparsable character(s)";
        static constexpr char const* UNEXPECTED_EOF_MESSAGE = "Unexpected end of file while parsing JSON document";

        JsonParseError(std::string const& msg):
            JsonException(msg) {}

        JsonParseError(std::string const& msg, std::size_t pos):
            JsonException(msg + " at position " + std::to_string(pos)) {}
    };

    class JsonTypeError : public JsonException
    {
    public:
        JsonTypeError(std::string const& msg) :
            JsonException(msg) {}
    };

    class JsonDepthLimitExceeded : public JsonException
    {
    public:
        static constexpr char const* DEPTH_LIMIT_EXCEEDED_MESSAGE
            = "Maximum nesting depth of " TO_STRING(MAX_NESTING_DEPTH) " exceeded";

        JsonDepthLimitExceeded(std::size_t pos):
            JsonException(DEPTH_LIMIT_EXCEEDED_MESSAGE + std::string(" at position ") + std::to_string(pos)) {}
    };

    class JsonOutOfRange : public JsonException
    {
    public:
        static constexpr char const* ARRAY_OUT_OF_RANGE_MESSAGE = "JSON array index out of range";
        static constexpr char const* KEY_NOT_FOUND_MESSAGE = "Key not found in JSON object";

        JsonOutOfRange(std::string const& msg):
            JsonException(msg) {}
    };
    /*
     * end JSON exceptions
     */
}

// ---- end: src/detail/jsonexception.hpp ----

// ---- begin: src/detail/json_fwd.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



namespace jsonpp
{
    using null_t = std::nullptr_t;
    constexpr null_t null = nullptr;

    template <
        template<typename U, typename V, typename... Args> class ObjectType = std::map,
        template<typename U, typename... Args> class ArrayType = std::vector,
        typename StringType = std::string,
        typename BooleanType = bool,
        typename NumberIntegerType = std::int64_t,
        typename NumberFloatType = double,
        template<typename U> class AllocatorType = std::allocator,
        // template<typename T, typename SFINAE = void> class JSONSerializer = adl_serializer, // 待实现
        // typename BinaryType = std::vector<std::uint8_t>, // 待实现
        typename CustomBaseClass = void
    >
    class basic_json;

    using json = basic_json<>;
    using unordered_json = basic_json<std::unordered_map>;

}
// ---- end: src/detail/json_fwd.hpp ----

// ---- begin: src/detail/json_serialize_handler.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



namespace jsonpp::details
{
    class StringSerializeHandler
    {
        std::string& m_buffer;

    public:
        explicit StringSerializeHandler(std::string& buf): m_buffer(buf) {}

        void append(char ch)
        {
            m_buffer.push_back(ch);
        }

        void append(std::string_view str)
        {
            m_buffer.append(str);
        }

        void append(char const* cstr, std::size_t length)
        {
            m_buffer.append(cstr, length);
        }
    };

    class OStreamSerializeHandler
    {
        std::ostream& m_out;

    public:
        explicit OStreamSerializeHandler(std::ostream& os): m_out(os) {}

        void append(char ch)
        {
            m_out.put(ch);
        }

        void append(std::string_view str)
        {
            m_out.write(str.data(), str.size());
        }

        void append(char const* cstr, std::size_t length)
        {
            m_out.write(cstr, length);
        }

        bool bad() const
        {
            return m_out.bad();
        }
    };

}


// ---- end: src/detail/json_serialize_handler.hpp ----

// ---- begin: src/detail/json_serializer.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */




namespace jsonpp::details
{
    template <typename JsonT, typename SerializeHandlerT>
    class JsonSerializer
    {
        static_assert(traits::is_json_serialize_handler_v<SerializeHandlerT>,
            "SerializeHandlerT should be a JSON Serialize Handler.");

        using boolean = typename JsonT::boolean;
        using number_int = typename JsonT::number_int;
        using number_float = typename JsonT::number_float;
        using string = typename JsonT::string;
        using array = typename JsonT::array;
        using object = typename JsonT::object;

        SerializeHandlerT& m_sh;

        static bool needs_escaping(char ch)
        {
            return ch == '\"' || ch == '\\' || static_cast<unsigned char>(ch) < 0x20
#ifdef ESCAPE_FORWARD_SLASH
            || ch == '/'
#endif
                ;
        }

        // 用于写入换行和当前的缩进
        void append_indent(std::string_view indent, int depth)
        {
            m_sh.append('\n');
            for (int i = 0; i < depth; ++i) {
                m_sh.append(indent);
            }
        }

    public:
        explicit JsonSerializer(SerializeHandlerT& handler) : m_sh(handler) {}

        template <typename StringT>
        void escape_string(StringT const& str) // escape v.转义 e.g. \ -> \\, " -> \"
        {
            std::string_view sv(std::data(str), std::size(str));
            m_sh.append('\"');
            auto chunkBegin = sv.begin();
            auto const end = sv.end();
            while (chunkBegin < end)
            {
                auto badChar = std::find_if(chunkBegin, end, needs_escaping);
                auto chunkLength = badChar - chunkBegin;
                if (chunkLength > 0)
                {
                    m_sh.append(std::addressof(*chunkBegin), chunkLength); // 第一个参数应当为指针而不是迭代器, 尽管部分实现中迭代器底层直接使用指针
                }
                if (badChar == end)
                    break; // 到达字符串结尾, 停止处理
                chunkBegin = badChar + 1; // 跳过当前已经写入流的块, 等同于 chunkBegin += chunkLength + 1

                // 下面处理转义
                char ch = *badChar;
                switch (ch)
                {
                case '\"': m_sh.append("\\\"", 2);
                    break;
                case '\\': m_sh.append("\\\\", 2);
                    break;
#ifdef ESCAPE_FORWARD_SLASH
                case '/': m_sh.append("\\/", 2); break;
#endif
                case '\b': m_sh.append("\\b", 2);
                    break; // \x08
                case '\f': m_sh.append("\\f", 2);
                    break; // \x0C
                case '\n': m_sh.append("\\n", 2);
                    break; // \x0A
                case '\r': m_sh.append("\\r", 2);
                    break; // \x0D
                case '\t': m_sh.append("\\t", 2);
                    break; // \x09
                default:
                    {
                        char buf[7]{};
                        std::snprintf(buf, sizeof(buf), "\\u%04x", static_cast<unsigned short>(ch));
                        m_sh.append(buf, 6); // \uXXXX一定是6字符
                        break;
                    }
                }
            }
            m_sh.append('\"');
        }

        template <bool Pretty = false>
        void dump(JsonT const& json, std::string_view indent = "\t", int depth = 0)
        {
            std::visit([this, &indent, depth](auto&& v)
                {
                    using T = std::decay_t<decltype(v)>;

                    if constexpr (std::is_same_v<T, std::monostate>)
                        return; // empty basic_json
                    if constexpr (std::is_same_v<T, null_t>)
                    {
                        m_sh.append("null", 4);
                    }
                    if constexpr (std::is_same_v<T, boolean>)
                    {
                        if (v) m_sh.append("true", 4);
                        else m_sh.append("false", 5);
                    }
                    if constexpr (std::is_same_v<T, number_int>)
                    {
                        constexpr size_t MAX_INT_CHARS = 32;
                        char cbuf[MAX_INT_CHARS];
                        auto result = std::to_chars(cbuf, cbuf + sizeof(cbuf), v);
                        m_sh.append(cbuf, result.ptr - cbuf);
                    }
                    if constexpr (std::is_same_v<T, number_float>)
                    {
                        constexpr size_t MAX_DOUBLE_CHARS = 64;
                        char cbuf[MAX_DOUBLE_CHARS];
                        auto result = std::to_chars(cbuf, cbuf + sizeof(cbuf), v, std::chars_format::general);
                        m_sh.append(cbuf, result.ptr - cbuf);

                        std::string_view written(cbuf, result.ptr - cbuf);
                        if (written.find('.') == std::string_view::npos &&
                            written.find('e') == std::string_view::npos &&
                            written.find('E') == std::string_view::npos)
                        {
                            m_sh.append(".0", 2); // ensure that float numbers have a decimal part
                        }
                    }
                    if constexpr (std::is_same_v<T, string>)
                    {
                        escape_string(v);
                    }
                    if constexpr (std::is_same_v<T, array>)
                    {
                        bool first = true;
                        m_sh.append('[');
                        if (!v.empty())
                        {
                            for (auto const& item : v)
                            {
                                if (!first)
                                    m_sh.append(',');
                                first = false;

                                if constexpr (Pretty)
                                    append_indent(indent, depth + 1);
                                dump<Pretty>(item);
                            }
                            if constexpr (Pretty)
                                append_indent(indent, depth);
                        }
                        m_sh.append(']');
                    }
                    if constexpr (std::is_same_v<T, object>)
                    {
                        bool first = true;
                        m_sh.append('{');
                        if (!v.empty())
                        {
                            for (auto const& item : v)
                            {
                                if (!first)
                                    m_sh.append(',');
                                first = false;

                                if constexpr (Pretty)
                                    append_indent(indent, depth + 1);
                                escape_string(item.first);
                                if constexpr (Pretty)
                                    m_sh.append(": ", 2);
                                else
                                    m_sh.append(':');
                                dump<Pretty>(item.second);
                            }
                            if constexpr (Pretty)
                                append_indent(indent, depth);
                        }
                        m_sh.append('}');
                    }
                }, json.m_value
            );
        }
    }; // class JsonSerializer

}

// ---- end: src/detail/json_serializer.hpp ----

// ---- begin: src/detail/json_stream_adaptor.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



namespace jsonpp
{
    namespace details
    {
        class StringViewStream
        {
            std::string_view m_data;
            std::size_t m_pos;

        public:
            int peek() const noexcept { if (m_pos < m_data.size()) return static_cast<unsigned char>(m_data[m_pos]); else return EOF; } // To ensure that 255 is correctly handled
            int advance() noexcept { if (m_pos < m_data.size()) return static_cast<unsigned char>(m_data[m_pos++]); else return EOF; }
            std::size_t tell_pos() const noexcept { return m_pos; }
            bool eof() const noexcept { return m_pos >= m_data.size(); }

            std::size_t size() const noexcept { return m_data.size(); }

            void seek(std::size_t step) noexcept
            {
                assert(m_pos + step <= m_data.size() && "StringViewStream::seek out of bounds!");
                m_pos += step;
            }

            std::string_view get_chunk(std::size_t begin, std::size_t length) const noexcept
            {
                assert(begin <= m_data.size() && "StringViewStream::get_chunk invalid begin!");
                return m_data.substr(begin, length);
            }

            template <typename FunctorT>
            std::string_view read_chunk_until(FunctorT predicate) &
            {
                std::string_view remaining = m_data.substr(m_pos);
                auto it = std::find_if(remaining.begin(), remaining.end(), predicate);
                auto chunk_size = std::distance(remaining.begin(), it);
                // Get chunk (if chunk_size=0, return empty view)
                std::string_view chunk = m_data.substr(m_pos, chunk_size);

                m_pos += chunk_size;

                return chunk;
            }
            explicit StringViewStream(std::string_view doc): m_data(doc), m_pos(0) {}
        };

        class IStreamStream
        {
            std::istream& m_is;
            std::size_t m_pos;
        public:
            int peek() const { return m_is.peek(); }
            int advance()
            {
                auto c = m_is.get();
                if (c != EOF)
                    ++m_pos;
                return c;
            }
            std::size_t tell_pos() const noexcept { return m_pos; }
            bool eof() const { return m_is.peek() == EOF; }

            explicit IStreamStream(std::istream& _is): m_is(_is), m_pos(0) { m_is.unsetf(std::ios::skipws); }
        };
    }
}
// ---- end: src/detail/json_stream_adaptor.hpp ----

// ---- begin: src/detail/basic_json.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */




namespace jsonpp
{
    namespace details
    {
        struct EmptyBaseClass {};
    }

    enum class Type: std::uint8_t
    {
        empty,
        null,
        boolean,
        number_int,
        number_float,
        string,
        array,
        object
    };

    BASIC_JSON_TEMPLATE
    class basic_json : public std::conditional_t<std::is_same_v<CustomBaseClass, void>, details::EmptyBaseClass, CustomBaseClass>
    {
        // =============================================================
        // * Internal Helper Types
        // =============================================================
    private:
        static constexpr bool _is_std_map =
            traits::details_t::is_std_map_v<ObjectType>;
        static constexpr bool _is_std_unordered_map =
            traits::details_t::is_std_unordered_map_v<ObjectType>;
        using _object_allocator_t = AllocatorType<std::pair<StringType const, basic_json>>;

        template <bool IsMapLike, bool IsUnorderedMapLike, typename Dummy = void>
        struct _object_type_selector
        {
            // assume it only needs K, V (non-standard container)
            using type = void;
        };

        template <typename Dummy>
        struct _object_type_selector<false, false, Dummy>
        {
            // assume it's a non-standard map container with 3 template parameters (Key, Value, Allocator)
            using type = ObjectType<StringType,
                                    basic_json,
                                    _object_allocator_t>;
        };

        template <typename Dummy>
        struct _object_type_selector<true, false, Dummy>
        {
            // assume it's a std::map-like container
            using type = ObjectType<StringType,
                                    basic_json,
                                    std::less<>,
                                    _object_allocator_t>;
        };

        template <typename Dummy>
        struct _object_type_selector<false, true, Dummy>
        {
            // assume it's a std::unordered_map-like container
            using type = ObjectType<StringType,
                                    basic_json,
                                    std::hash<StringType>,
                                    std::equal_to<StringType>,
                                    _object_allocator_t>;
        };

        // =============================================================
        //  * Public Types & Aliases
        // =============================================================
    public:
        using boolean = BooleanType;
        using number_int = NumberIntegerType;
        using number_float = NumberFloatType;
        using string = StringType;
        using array = ArrayType<basic_json, AllocatorType<basic_json>>;
        using object = typename _object_type_selector<_is_std_map, _is_std_unordered_map>::type;
        using json_t = BASIC_JSON_TYPE;
        using value_t = std::variant <
            std::monostate,
            null_t,
            boolean,
            number_int,
            number_float,
            string,
            array,
            object
        >;

        // Iterator Support
        using iterator = null_t;
        using const_iterator = null_t;
        using reverse_iterator = std::reverse_iterator<iterator>;
        using const_reverse_iterator = std::reverse_iterator<const_iterator>;

        // [STL Compatibility] Standard container aliases
        using value_type = basic_json;
        using allocator_type = AllocatorType<value_type>;
        using size_type = std::size_t;
        using difference_type = std::ptrdiff_t;
        using reference = value_type&;
        using const_reference = value_type const&;
        using pointer = value_type*;
        using const_pointer = value_type const*;

        template <typename T>
        constexpr static bool is_json_value_type =
            std::is_same_v<T, std::monostate> ||
            std::is_same_v<T, null_t> ||
            std::is_same_v<T, bool> ||
            std::is_same_v<T, boolean> ||
            std::is_integral_v<T> ||
            std::is_same_v<T, number_int> ||
            std::is_floating_point_v<T> ||
            std::is_same_v<T, number_float> ||
            std::is_convertible_v<T, string> ||
            std::is_same_v<T, array> ||
            std::is_same_v<T, object>;

        // =============================================================
        //  * Lifecycle (Constructors, Destructor, Assignment)
        // =============================================================
    public:
        basic_json() = default;
        ~basic_json() = default;

        // Type constructors
        basic_json(null_t): m_value(null_t()) {}
        explicit basic_json(boolean val): m_value(val) {}
        // Constructor for integral types (including char, which will be treated as an integer)
        template <typename T_Integer,
            std::enable_if_t<std::is_integral_v<T_Integer>, int> = 0>
        basic_json(T_Integer val): m_value(val) {}
        basic_json(number_int val): m_value(val) {}
        // Constructor for floating-point types
        template <typename T_Float,
            std::enable_if_t<std::is_floating_point_v<T_Float>, int> = 0>
        basic_json(T_Float val): m_value(val) {}
        basic_json(number_float val): m_value(val) {}
        basic_json(string val): m_value(std::move(val)) {}
        basic_json(char const* val): m_value(val) {}
        explicit basic_json(std::string_view val): m_value(string(val)) {} // Explicit to prevent expensive, implicit copies from a non-owning string_view.
        basic_json(array val): m_value(std::move(val)) {}
        basic_json(object val): m_value(std::move(val)) {}

        // Copy and move
        basic_json(basic_json const& other) = default;
        basic_json(basic_json&& other) noexcept = default;
        reference operator=(basic_json const& other) = default;
        reference operator=(basic_json&& other) noexcept = default;

        // Templated assignment
        template <typename T,
            std::enable_if_t<is_json_value_type<std::decay_t<T>> &&
                            !std::is_same_v<std::decay_t<T>, basic_json>, int> = 0>
        reference operator=(T&& val) { m_value = std::forward<T>(val); return *this; }

        // =============================================================
        //  * Capacity & Property (查询状态)
        //  (新增：size, max_size, capacity, reserve, shrink_to_fit)
        // =============================================================
    public:
        Type type() const noexcept { return static_cast<Type>(m_value.index()); }

        template <Type T>
        void set_type(bool clear_content = false);
        void set_type(Type const& t, bool clear_content = false);

        // State Checkers
        bool empty() const noexcept { return std::holds_alternative<std::monostate>(m_value); }
        size_type size() const noexcept;       // [New]
        size_type max_size() const noexcept;   // [New]
        size_type capacity() const;            // [New] (Array only)

        // Capacity Modifiers (虽是修改，但归类于容量更直观)
        void reserve(size_type new_cap);       // [New] (Array/Object)
        void shrink_to_fit();                  // [New] (Array/String)

        // Type Predicates
        bool is_null() const noexcept { return std::holds_alternative<null_t>(m_value); }
        bool is_bool() const noexcept { return std::holds_alternative<boolean>(m_value); }
        bool is_number() const noexcept { return std::holds_alternative<number_int>(m_value) || std::holds_alternative<number_float>(m_value); }
        bool is_int() const noexcept { return std::holds_alternative<number_int>(m_value); }
        bool is_float() const noexcept { return std::holds_alternative<number_float>(m_value); }
        bool is_string() const noexcept { return std::holds_alternative<string>(m_value); }
        bool is_array() const noexcept { return std::holds_alternative<array>(m_value); }
        bool is_object() const noexcept { return std::holds_alternative<object>(m_value); }

        // =============================================================
        //  * Element Access (获取数据)
        //  (新增：front, back, value)
        // =============================================================
    public:
        // Array access
        reference operator[](size_type index);
        value_type const& operator[](size_type index) const;
        reference at(size_type index);
        value_type const& at(size_type index) const;
        // Object access
        reference operator[](std::string const& key);
        value_type const& operator[](std::string const& key) const;
        reference at(std::string const& key);
        value_type const& at(std::string const& key) const;

        // [New] Front & Back (Array only)
        reference front();
        const_reference front() const;
        reference back();
        const_reference back() const;

        // [New] Value with Default (Object only)
        template <typename ValueType>
        ValueType value(string const& key, ValueType const& default_value) const;

        // =============================================================
        //  * Lookup (Object 查找)
        //  (新增：find, count, contains)
        // =============================================================
    public:
        // [New] Find
        iterator find(string const& key);
        const_iterator find(string const& key) const;

        // [New] Count & Contains
        size_type count(string const& key) const;
        bool contains(string const& key) const;

        // =============================================================
        //  * Iterators
        //  (待实现，先占位)
        // =============================================================
    public:
        iterator begin();
        const_iterator begin() const;
        const_iterator cbegin() const;
        iterator end();
        const_iterator end() const;
        const_iterator cend() const;
        reverse_iterator rbegin();
        const_reverse_iterator rbegin() const;
        const_reverse_iterator crbegin() const;
        reverse_iterator rend();
        const_reverse_iterator rend() const;
        const_reverse_iterator crend() const;

        // =============================================================
        //  * Modifiers (修改内容)
        //  (新增：clear, pop_back, insert, erase, update, resize, swap)
        // =============================================================
    public:
        // General
        void clear() noexcept;
        void swap(reference other) noexcept { m_value.swap(other.m_value); }
        friend void swap(reference lhs, reference rhs) noexcept { lhs.m_value.swap(rhs.m_value); } // for ADL (Argument-Dependent Lookup)

        // Array Modifiers
        void push_back(basic_json&& val);
        void push_back(const_reference val);
        template <typename... Args>
        reference emplace_back(Args&&... args);
        void pop_back();

        // Resize (Array)
        void resize(size_type new_size);
        void resize(size_type new_size, const_reference value);

        // Object/Array Insertion
        // [New] Insert (Range)
        template <typename InputIt>
        void insert(InputIt first, InputIt last);

        // [New] Insert (Init List)
        void insert(std::initializer_list<basic_json> il);

        // [New] Insert (Pair - Existing but improved signatures?)
        auto insert(std::pair<string, basic_json> const& pair);
        auto insert(std::pair<string, basic_json>&& pair);

        // [New] Insert at pos (Array) - Blocked until iterator ready
        iterator insert(const_iterator pos, const_reference val);

        // Emplace (Object)
        template <typename... Args>
        auto emplace(Args&&... args);
        template <typename... Args>
        std::pair<iterator, bool> try_emplace(string const& key, Args&&... args);

        // Object/Array Erasure
        // [New] Erase by Key
        size_type erase(string const& key);
        // [New] Erase by Index
        void erase(size_type index);
        // [New] Erase by Iterator - Blocked
        iterator erase(const_iterator pos);
        iterator erase(const_iterator first, const_iterator last);

        // Object Merge
        // [New] Update
        void update(const_reference other, bool merge_objects = false);
        void update(const_iterator first, const_iterator last, bool merge_objects = false);

        // =============================================================
        //  * Conversions (类型转换)
        // =============================================================
    public:
        // Pointers (Safe)
        boolean const* get_if_bool() const noexcept { return std::get_if<boolean>(&m_value); }
        boolean* get_if_bool() noexcept { return std::get_if<boolean>(&m_value); }

        number_int const* get_if_int() const noexcept { return std::get_if<number_int>(&m_value); }
        number_int* get_if_int() noexcept { return std::get_if<number_int>(&m_value); }

        number_float const* get_if_float() const noexcept { return std::get_if<number_float>(&m_value); }
        number_float* get_if_float() noexcept { return std::get_if<number_float>(&m_value); }

        std::string const* get_if_string() const noexcept { return std::get_if<string>(&m_value); }
        string* get_if_string() noexcept { return std::get_if<string>(&m_value); }

        array const* get_if_array() const noexcept { return std::get_if<array>(&m_value); }
        array* get_if_array() noexcept { return std::get_if<array>(&m_value); }

        object const* get_if_object() const noexcept { return std::get_if<object>(&m_value); }
        object* get_if_object() noexcept { return std::get_if<object>(&m_value); }

        // References (Asserted)
        boolean as_bool() const { return as_impl<boolean>(m_value, "bool"); }
        boolean& as_bool() { return as_impl<boolean>(m_value, "bool"); }

        number_int as_int() const { return as_impl<number_int>(m_value, "int64"); }
        number_int& as_int() { return as_impl<number_int>(m_value, "int64"); }

        number_float as_float() const { return as_impl<number_float>(m_value, "double"); }
        number_float& as_float() { return as_impl<number_float>(m_value, "double"); }

        string const& as_string() const { return as_impl<string>(m_value, "string"); }
        std::string& as_string() { return as_impl<string>(m_value, "string"); }

        array const& as_array() const { return as_impl<array>(m_value, "array"); }
        array& as_array() { return as_impl<array>(m_value, "array"); }

        object const& as_object() const { return as_impl<object>(m_value, "object"); }
        object& as_object() { return as_impl<object>(m_value, "object"); }

        // =============================================================
        //  * Operators & Serialization
        // =============================================================
    public:
        bool operator==(const_reference other) const;
        bool operator!=(const_reference other) const { return !(*this == other); }

        static basic_json parse(std::string_view json_doc);
        static basic_json parse(std::istream& json_istream);
        template <typename StreamT,
            std::enable_if_t<traits::is_json_stream_v<StreamT>, int> = 0>
        static basic_json parse(StreamT& stream);

        void dump(std::string& buffer, bool pretty = false, std::string_view indent = "\t") const;
        void dump(std::ostream& os, bool pretty = false, std::string_view indent = "\t") const;
        template <typename SerializeHandlerT,
            std::enable_if_t<traits::is_json_serialize_handler_v<SerializeHandlerT>, int> = 0>
        void dump(SerializeHandlerT& handler, bool pretty = false, std::string_view indent = "\t") const;

        std::string stringify() const;
        std::string pretty(std::string_view indent = "\t") const;

        // =============================================================
        //  * Private Implementation
        // =============================================================
    private:
        template <typename JsonT, typename SerializeHandlerT>
        friend class details::JsonSerializer;

    private:
        value_t m_value;

    private:
        // [To Implement] 必须存储 Allocator 实例，否则无法支持 Stateful Allocator
        // [[no_unique_address]] AllocatorType m_allocator = AllocatorType();

        // [新增] 统一的内部容器创建函数 (建议实现)
        template <typename ContainerType>
        void create_container();

        template <Type T>
        void set_type_impl();

        template <typename T>
        static T& as_impl(value_t& v, char const* typeName);

        template <typename T>
        static T const& as_impl(value_t const& v, char const* typeName);

    }; // class basic_json

    // The stream itself has the function of adding \ (escaping) to characters that need to be escaped. This process occurs from memory to the stream.
    BASIC_JSON_TEMPLATE
    std::ostream& operator<<(std::ostream& os, BASIC_JSON_TYPE const& val)
    {
        val.dump(os);
        return os;
    }


} // namespace jsonpp

// ---- end: src/detail/basic_json.hpp ----

// ---- begin: src/detail/parser.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */




namespace jsonpp
{
    using namespace traits;

    namespace details
    {
        /*
         * ParserBase
         */
        template <typename StreamT>
        class ParserBase
        {
            static_assert(is_json_stream_v<StreamT>, "StreamT should be a JSON Stream.");

        protected:
            StreamT& m_stream;

        public:
            int peek() const noexcept { return m_stream.peek(); }
            int advance() noexcept { return m_stream.advance(); }
            std::size_t tell_pos() const noexcept { return m_stream.tell_pos(); }
            bool eof() const noexcept { return m_stream.eof(); }

            template <typename ExceptionT>
            void consume(char expected, ExceptionT const& e) { if (advance() == expected); else throw e; }

            std::size_t size() const { if constexpr (is_sized_stream_v<StreamT>) { return m_stream.size(); }
                else { static_assert(false, ".size() was called, but the stream is not a Sized Stream."); } }

            void seek(std::size_t step) { if constexpr (is_seekable_stream_v<StreamT>) { m_stream.seek(step); }
                else { static_assert(false, ".seek() was called, but the stream is not a Seekable Stream."); } }

            std::string_view get_chunk(std::size_t begin, std::size_t length) { if constexpr (is_contiguous_stream_v<StreamT>) { return m_stream.get_chunk(begin, length); }
                else { static_assert(false, ".get_chunk() was called, but the stream is not a Contiguous Stream."); } }

            template <typename FunctorT>
            std::string_view read_chunk_until(FunctorT predicate) { if constexpr (is_contiguous_stream_v<StreamT>) { return m_stream.read_chunk_until(predicate); }
                else { static_assert(false, ".get_chunk_until() was called, but the stream is not a Contiguous Stream."); } }

            explicit ParserBase(StreamT& stream): m_stream(stream) {}
        };
        /*
         * end ParserBase
         */

        /*
         * JSONStringParser
         */
        template <typename StreamT, typename JsonT>
        class JSONStringParser : public ParserBase<StreamT>
        {
        protected:
            JSONPP_IMPORT_PARSERBASE_MEMBERS_

            using string = typename JsonT::string;

        private:
            string m_result;
            std::size_t m_start;

            enum class UCPStatus: std::uint8_t // Unicode Code Point Status
            {
                SINGLE,
                HIGH,
                LOW
            };

            struct hex4_result
            {
                std::uint16_t value = 0;
                UCPStatus type = UCPStatus::SINGLE;
            };

            hex4_result read_hex4(std::size_t upos);
            void append_utf8(std::uint32_t codepoint);
            static std::uint32_t get_codepoint(std::uint16_t high, std::uint16_t low);
            void unescape_character();

        public:
            JSONStringParser(StreamT& stream, std::size_t _start): ParserBase<StreamT>(stream), m_result(), m_start(_start) {}
            string parse();

        };

        template <typename StreamT, typename JsonT>
        typename JSONStringParser<StreamT, JsonT>::hex4_result JSONStringParser<StreamT, JsonT>::read_hex4(std::size_t upos)
        {
            std::uint16_t value;
            char num_buf[4];
            for (int i = 0; i < 4; ++i)
                num_buf[i] = advance();
            JSONPP_CHECK_EOF_("string", m_start);

            auto [ptr, ec] = std::from_chars(num_buf, num_buf + 4, value, 16);
            if (ec == std::errc() && ptr == num_buf + 4)
            {
                UCPStatus type;
                if (value >= 0xD800 && value <= 0xDBFF)
                    type = UCPStatus::HIGH;
                else if (value >= 0xDC00 && value <= 0xDFFF)
                    type = UCPStatus::LOW;
                else
                    type = UCPStatus::SINGLE;
                return {value, type};
            }
            else throw JsonParseError("Invalid hexadecimal digits found in Unicode escape sequence", upos);
        }

        template <typename StreamT, typename JsonT>
        void JSONStringParser<StreamT, JsonT>::append_utf8(std::uint32_t codepoint)
        {
            if (codepoint <= 0x7F)
            {
                // ASCII, 0b0xxxxxxx
                m_result += static_cast<char>(codepoint);
            }
            else if (codepoint <= 0x7FF)
            {
                // 2-byte UTF-8, 0b110xxxxx 0b10xxxxxx
                m_result += static_cast<char>(0xC0 | ((codepoint >> 6) & 0x1F));
                m_result += static_cast<char>(0x80 | (codepoint & 0x3F));
            }
            else if (codepoint <= 0xFFFF)
            {
                // 3-byte UTF-8, 0b1110xxxx 0b10xxxxxx 0b10xxxxxx
                m_result += static_cast<char>(0xE0 | ((codepoint >> 12) & 0x0F));
                m_result += static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F));
                m_result += static_cast<char>(0x80 | (codepoint & 0x3F));
            }
            else if (codepoint <= 0x10FFFF)
            {
                // 4-byte UTF-8, 0b11110xxx 0b10xxxxxx 0b10xxxxxx 0b10xxxxxx
                m_result += static_cast<char>(0xF0 | (codepoint >> 18));
                m_result += static_cast<char>(0x80 | ((codepoint >> 12) & 0x3F));
                m_result += static_cast<char>(0x80 | ((codepoint >> 6) & 0x3F));
                m_result += static_cast<char>(0x80 | (codepoint & 0x3F));
            }
        }

        template <typename StreamT, typename JsonT>
        std::uint32_t JSONStringParser<StreamT, JsonT>::get_codepoint(std::uint16_t high, std::uint16_t low)
        {
            return
                0x10000 | (((std::uint32_t)high & 0x03FF) << 10) | ((std::uint32_t)low & 0x03FF);
        }

        template <typename StreamT, typename JsonT>
        void JSONStringParser<StreamT, JsonT>::unescape_character()
        {
            switch (peek())
            {
            case '\"': m_result += '\"'; advance(); break;
            case '\\': m_result += '\\'; advance(); break;
            case '/': m_result += '/'; advance(); break;
            case 'b': m_result += '\b'; advance(); break;
            case 'f': m_result += '\f'; advance(); break;
            case 'n': m_result += '\n'; advance(); break;
            case 'r': m_result += '\r'; advance(); break;
            case 't': m_result += '\t'; advance(); break;
            case 'u':
                {
                    auto upos = tell_pos();
                    advance();

                    auto [cp, type] = read_hex4(upos);

                    switch (type)
                    {
                    case UCPStatus::SINGLE:
                        append_utf8(cp);
                        break;
                    case UCPStatus::HIGH:
                        {
                            consume('\\', JsonParseError("Expected low surrogate after high surrogate in Unicode escape sequence", tell_pos()));
                            consume('u', JsonParseError("Expected low surrogate after high surrogate in Unicode escape sequence", tell_pos()));
                            auto [cp_low, type_low] = read_hex4(upos);
                            if (type_low != UCPStatus::LOW)
                                throw JsonParseError("Expected low surrogate after high surrogate in Unicode escape sequence", tell_pos());

                            append_utf8(get_codepoint(cp, cp_low));
                            break;
                        }
                    case UCPStatus::LOW:
                        throw JsonParseError("Unexpected low surrogate without preceding high surrogate", upos);
                    }
                    break;
                }
            default:
                throw JsonParseError("Invalid escape character", tell_pos());
            }
        }

        template <typename StreamT, typename JsonT>
        typename JSONStringParser<StreamT, JsonT>::string JSONStringParser<StreamT, JsonT>::parse()
        {
            advance(); // 字符串起点, 跳过左引号

            if constexpr (is_sized_stream_v<StreamT>)
            { // 如果能直接得到整个流的大小则直接预留空间
                m_result.reserve(size());
            }

            while (!eof())
            {
                if constexpr (is_contiguous_stream_v<StreamT>)
                {
                    std::string_view chunk = read_chunk_until([](char c)
                    { // 需要终止搜索的字符, 分别代表转义, 结束, 控制字符(需转义)
                        return c == '\\' || c == '\"' || static_cast<unsigned char>(c) < 0x20;
                    });

                    if (!chunk.empty())
                        m_result.append(chunk);
                    JSONPP_CHECK_EOF_("string", m_start);
                }
                // 下面检查为什么停下

                int ch = peek();
                if (ch == '\"')
                    break;

                if (ch == '\\')
                {
                    advance();
                    unescape_character();
                }
                // JSON 规范 (RFC 8259) 禁止未转义的控制字符 (U+0000 到 U+001F)
                else if (ch < 0x20)
                    throw JsonParseError("Unescaped control character in string", tell_pos());
                else
                {
                    // 只有 IStreamStream 会在这里命中好字符, StringViewStream 已经在 chunk 中处理了它们
                    m_result += ch;
                    advance();
                }
            }
            JSONPP_CHECK_EOF_("string", m_start);

            advance(); // 跳过右引号
            return std::move(m_result);
        }
        /*
         * end JSONStringParser
         */

        /*
         * JSON Parser
         */
        template <typename StreamT, typename JsonT>
        class Parser : public ParserBase<StreamT>
        {
        protected:
            JSONPP_IMPORT_PARSERBASE_MEMBERS_

            using boolean = typename JsonT::boolean;
            using number_int = typename JsonT::number_int;
            using number_float = typename JsonT::number_float;
            using string = typename JsonT::string;
            using array = typename JsonT::array;
            using object = typename JsonT::object;

        private:
            int m_nesting_depth;

            static bool is_whitespace(char ch) noexcept;

            void skip_whitespace() noexcept; // 跳过从 pos 开始的空白字符, 使 pos 指向调用函数后的第一个非空白字符

            void parse_literal(char const* lit, std::size_t len);

            static JsonT parse_number_from_chunk(std::string_view chunk, std::size_t start);

            JsonT parse_value(); // 解析, 返回并跳过从当前 pos 开始的一个 basic_json, 使 pos 指向被解析的 basic_json 后的第一个字节

            JsonT parse_null();
            JsonT parse_true();
            JsonT parse_false();
            JsonT parse_number();
            JsonT parse_string();
            JsonT parse_array();
            JsonT parse_object();

        public:
            Parser() = delete;

            explicit Parser(StreamT& stream) : ParserBase<StreamT>(stream), m_nesting_depth(0) {}

            JsonT parse();
        };

        template <typename StreamT, typename JsonT>
        void Parser<StreamT, JsonT>::parse_literal(char const* lit, std::size_t len)
        {
            for (std::size_t i = 0; i < len; ++i)
            {
                consume(lit[i], JsonParseError(JsonParseError::UNPARSABLE_MESSAGE, tell_pos()));
            }
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_number_from_chunk(std::string_view chunk, std::size_t start)
        {
            std::int64_t val_i{};
            auto res_i = std::from_chars(chunk.data(), chunk.data() + chunk.size(), val_i);
            if (res_i.ptr == chunk.data() + chunk.size() && res_i.ec == std::errc()) // 成功
            {
                return {val_i};
            }

            double val_f{};
            auto res_f = std::from_chars(chunk.data(), chunk.data() + chunk.size(), val_f);
            if (res_f.ptr == chunk.data() + chunk.size() && res_f.ec == std::errc()) // 成功
            {
                return {val_f};
            }

            if (res_f.ec == std::errc::result_out_of_range)
                throw JsonParseError("Number is out of range", start);
            else
                throw JsonParseError(JsonParseError::UNPARSABLE_MESSAGE, res_f.ptr - chunk.data());

        }

        template <typename StreamT, typename JsonT>
        bool Parser<StreamT, JsonT>::is_whitespace(char ch) noexcept
        {
            return ch == ' ' || ch == '\n' || ch == '\r' || ch == '\t';
        }

        template <typename StreamT, typename JsonT>
        void Parser<StreamT, JsonT>::skip_whitespace() noexcept
        {
            while (is_whitespace(peek()))
                advance();
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_value()
        {
            // 调用该函数之前与之后均调用了 skip_whitespace()
            if (eof())
                throw JsonParseError("Unexpected end of file");
            char ch = peek();
            switch (ch)
            {
            case 'n':
                return parse_null();
            case 't':
                return parse_true();
            case 'f':
                return parse_false();
            case '\"':
                return parse_string();
            case '[':
                return parse_array();
            case '{':
                return parse_object();
            default:
                if ((ch >= '0' && ch <= '9') || ch == '-')
                    return parse_number();
                throw JsonParseError(JsonParseError::UNPARSABLE_MESSAGE, tell_pos());
            }
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_null()
        {
            parse_literal("null", 4);
            return {null};
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_true()
        {
            parse_literal("true", 4);
            return JsonT(true);
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_false()
        {
            parse_literal("false", 5);
            return JsonT(false);
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_number()
        {
            auto is_num_char = [](char c) -> bool {
                return isdigit(static_cast<unsigned char>(c))
                    || c == '.' || c == '-' || c == '+' || c == 'e' || c == 'E';
            };

            std::size_t start = tell_pos();

            if constexpr (is_contiguous_stream_v<StreamT>)
            {
                while (is_num_char(peek()))
                    advance();
                return parse_number_from_chunk(get_chunk(start, tell_pos() - start), start);
            }
            else
            {
                std::string chunk;
                while (is_num_char(peek()))
                {
                    chunk += advance(); // 停在第 1 个不可能是数字字符的位置
                }
                return parse_number_from_chunk(chunk, start);
            }

        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_string()
        {
            return JSONStringParser<StreamT, JsonT>(m_stream, tell_pos()).parse();
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_array()
        {
            // Increase nesting depth counter and check limit
            if (++m_nesting_depth > MAX_NESTING_DEPTH)
                throw JsonDepthLimitExceeded(tell_pos());

            array arr;
            auto start = tell_pos(); // 跳过左 [
            advance();
            skip_whitespace();
            while (!eof() && peek() != ']')
            {
                arr.push_back(parse_value());
                skip_whitespace();

                // json数组中对象以外的字符只能是空白字符或'['或']'或','
                if (peek() == ']')
                    break;
                else if (peek() != ',')
                {
                    JSONPP_CHECK_EOF_("array", start);
                    throw JsonParseError(JsonParseError::UNPARSABLE_MESSAGE, tell_pos());
                }
                advance(); // 跳过 ','

                skip_whitespace();

                if (peek() == ']')
                    throw JsonParseError("Expected value after comma, but found ']' instead", tell_pos());
            }
            JSONPP_CHECK_EOF_("array", start);

            advance(); // 跳过右 ]
            --m_nesting_depth; // Decrease nesting depth counter before returning
            return {arr};
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse_object()
        {
            // Increase nesting depth counter and check limit
            if (++m_nesting_depth > MAX_NESTING_DEPTH)
                throw JsonDepthLimitExceeded(tell_pos());

            object obj;
            auto start = tell_pos(); // 跳过左 {
            advance();
            skip_whitespace();
            while (!eof() && peek() != '}')
            {
                auto key = parse_value();

                if (!key.is_string()) [[unlikely]]
                    throw JsonParseError("Key of an object must be string");

                skip_whitespace();

                if (peek() != ':')
                {
                    JSONPP_CHECK_EOF_("object", start);
                    throw JsonParseError(JsonParseError::UNPARSABLE_MESSAGE, tell_pos());
                }
                advance();

                skip_whitespace();
                auto val = parse_value();
                obj[key.as_string()] = val;

                skip_whitespace();

                if (peek() == '}')
                    break;
                else if (peek() != ',')
                {
                    JSONPP_CHECK_EOF_("object", start);
                    throw JsonParseError(JsonParseError::UNPARSABLE_MESSAGE, tell_pos());
                }
                advance(); // skip comma

                skip_whitespace();

                if (peek() == '}')
                    throw JsonParseError("Expected value after comma, but found '}' instead", tell_pos());
            }
            JSONPP_CHECK_EOF_("object", start);

            advance(); // 跳过右 }
            --m_nesting_depth; // Decrease nesting depth counter before returning
            return {obj};
        }

        template <typename StreamT, typename JsonT>
        JsonT Parser<StreamT, JsonT>::parse()
        {
            skip_whitespace();
            if (eof()) // doc 为空
                return {};

            auto val = parse_value();
            skip_whitespace();

            if (eof()) // 表示恰好解析整个文档
                return val;
            else
                throw JsonParseError("Unexpected character(s) after JSON value");

            return {};
        }
        /*
         * end JSON Parser
         */
    }

}

// ---- end: src/detail/parser.hpp ----

// ---- begin: src/detail/basic_json_impl.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



namespace jsonpp
{
    using namespace traits;

    BASIC_JSON_TEMPLATE
    template <Type T>
    void BASIC_JSON_TYPE::set_type_impl()
    {
        if constexpr (T == Type::empty)
            m_value.template emplace<std::monostate>();
        else if constexpr (T == Type::null)
            m_value.template emplace<null_t>();
        else if constexpr (T == Type::object)
            m_value.template emplace<object>();
        else if constexpr (T == Type::array)
            m_value.template emplace<array>();
        else if constexpr (T == Type::string)
            m_value.template emplace<string>();
        else if constexpr (T == Type::boolean)
            m_value.template emplace<boolean>(false);
        else if constexpr (T == Type::number_int)
            m_value.template emplace<number_int>(0);
        else if constexpr (T == Type::number_float)
            m_value.template emplace<number_float>(0.0);
    }

    BASIC_JSON_TEMPLATE
    template <typename T>
    T& BASIC_JSON_TYPE::as_impl(value_t& v, char const* typeName)
    {
        try
        {
            return std::get<T>(v);
        }
        catch (const std::bad_variant_access&)
        {
            throw JsonTypeError(std::string("Value is not a ") + typeName);
        }
    }

    BASIC_JSON_TEMPLATE
    template <typename T>
    T const& BASIC_JSON_TYPE::as_impl(value_t const& v, char const* typeName)
    {
        try
        {
            return std::get<T>(v);
        }
        catch (const std::bad_variant_access&)
        {
            throw JsonTypeError(std::string("Value is not a ") + typeName);
        }
    }

    BASIC_JSON_TEMPLATE
    template <Type T>
    void BASIC_JSON_TYPE::set_type(bool clear_content)
    {
        if (!clear_content && type() == T) return; // do nothing if already of type T
        set_type_impl<T>();
    }

    BASIC_JSON_TEMPLATE
    void BASIC_JSON_TYPE::set_type(Type const& t, bool clear_content)
    {
        if (!clear_content && type() == t) return;

        switch (t)
        {
        case Type::empty:       set_type_impl<Type::empty>(); break;
        case Type::null:        set_type_impl<Type::null>(); break;
        case Type::boolean:     set_type_impl<Type::boolean>(); break;
        case Type::number_int:  set_type_impl<Type::number_int>(); break;
        case Type::number_float:set_type_impl<Type::number_float>(); break;
        case Type::string:      set_type_impl<Type::string>(); break;
        case Type::array:       set_type_impl<Type::array>(); break;
        case Type::object:      set_type_impl<Type::object>(); break;
        default:
#if defined(__GNUC__) || defined(__clang__)
            __builtin_unreachable();
#elif defined(_MSC_VER)
            __assume(0);
#endif
            break;
        }
    }

    BASIC_JSON_TEMPLATE
    typename BASIC_JSON_TYPE::size_type BASIC_JSON_TYPE::size() const noexcept
    {
        switch (type())
        {
        case Type::empty:
        case Type::null:
            return 0;
        case Type::boolean:
        case Type::number_int:
        case Type::number_float:
        case Type::string:
            return 1;
        case Type::array:
            return as_array().size();
        case Type::object:
            return as_object().size();
        default:
#if defined(__GNUC__) || defined(__clang__)
            __builtin_unreachable();
#elif defined(_MSC_VER)
            __assume(0);
#endif
        }
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE& BASIC_JSON_TYPE::operator[](size_type index)
    {
        return const_cast<basic_json&>(
            static_cast<basic_json const&>(*this).operator[](index)
        );
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE const& BASIC_JSON_TYPE::operator[](size_type index) const
    {
        auto const& arr = as_array();
        assert(index < arr.size() && "JSON array index out of range");
        return arr[index];
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE& BASIC_JSON_TYPE::at(size_type index)
    {
        return const_cast<basic_json&>(
            static_cast<basic_json const&>(*this).at(index)
        );
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE const& BASIC_JSON_TYPE::at(size_type index) const
    {
        auto const& arr = as_array();
        if (index >= arr.size())
            throw JsonOutOfRange(JsonOutOfRange::ARRAY_OUT_OF_RANGE_MESSAGE);
        return arr[index];
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE& BASIC_JSON_TYPE::operator[](std::string const& key)
    {
        if (empty() || is_null())
            set_type(Type::object);

        return as_object()[key];
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE const& BASIC_JSON_TYPE::operator[](std::string const& key) const
    {
        return at(key);
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE& BASIC_JSON_TYPE::at(std::string const& key)
    {
        return const_cast<basic_json&>(
            static_cast<basic_json const&>(*this).at(key)
        );
    }

    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE const& BASIC_JSON_TYPE::at(std::string const& key) const
    {
        auto const& obj = as_object();
        auto it = obj.find(key);
        if (it == obj.end())
            throw JsonOutOfRange(JsonOutOfRange::KEY_NOT_FOUND_MESSAGE);
        return it->second;
    }

    BASIC_JSON_TEMPLATE
    bool BASIC_JSON_TYPE::contains(string const& key) const
    {
        if (!is_object())
            return false;
        auto& obj = as_object();
        return obj.find(key) != obj.end();
    }

    BASIC_JSON_TEMPLATE
    void BASIC_JSON_TYPE::push_back(BASIC_JSON_TYPE&& val)
    {
        if (empty() || is_null())
            set_type<Type::array>();
        as_array().emplace_back(std::move(val));
    }

    BASIC_JSON_TEMPLATE
    void BASIC_JSON_TYPE::push_back(BASIC_JSON_TYPE const& val)
    {
        if (empty() || is_null())
            set_type<Type::array>();
        as_array().emplace_back(val);
    }

    BASIC_JSON_TEMPLATE
    template <typename... Args>
    BASIC_JSON_TYPE& BASIC_JSON_TYPE::emplace_back(Args&&... args)
    {
        if (empty() || is_null())
            set_type<Type::array>();
        return as_array().emplace_back(std::forward<Args>(args)...);
    }

    BASIC_JSON_TEMPLATE
    auto BASIC_JSON_TYPE::insert(std::pair<string, basic_json> const& pair)
    {
        if (empty() || is_null())
            set_type<Type::object>();
        return as_object().insert(pair);
    }

    BASIC_JSON_TEMPLATE
    auto BASIC_JSON_TYPE::insert(std::pair<string, basic_json>&& pair)
    {
        if (empty() || is_null())
            set_type(Type::object);
        return as_object().emplace(std::move(pair));
    }

    BASIC_JSON_TEMPLATE
    template <typename... Args>
    auto BASIC_JSON_TYPE::emplace(Args&&... args)
    {
        if (empty() || is_null())
            set_type<Type::object>();
        return as_object().emplace(std::forward<Args>(args)...);
    }

    BASIC_JSON_TEMPLATE
    bool BASIC_JSON_TYPE::operator==(BASIC_JSON_TYPE const& other) const
    {
        if (m_value.index() != other.m_value.index()) return false;
        return m_value == other.m_value;
    }

    /*
     * Parse a document to JsonType, accessing data with std::string_view.
     */
    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE BASIC_JSON_TYPE::parse(std::string_view json_doc)
    {
        details::StringViewStream svs(json_doc);
        return details::Parser<details::StringViewStream, basic_json>(svs).parse();
    }

    /*
     * Parse a document to JsonType, accessing data with std::istream.
     */
    BASIC_JSON_TEMPLATE
    BASIC_JSON_TYPE BASIC_JSON_TYPE::parse(std::istream& json_istream)
    {
        details::IStreamStream iss(json_istream);
        return details::Parser<details::IStreamStream, basic_json>(iss).parse();
    }

    /*
     * Parse a document to JsonType, accessing data with a JSON Stream.
     * Data should have been provided to the stream before calling this function.
     */
    BASIC_JSON_TEMPLATE
    template <typename StreamT,
        std::enable_if_t<traits::is_json_stream_v<StreamT>, int>>
    BASIC_JSON_TYPE BASIC_JSON_TYPE::parse(StreamT& stream)
    {
        return details::Parser<StreamT, basic_json>(stream).parse();
    }

    BASIC_JSON_TEMPLATE
    void BASIC_JSON_TYPE::dump(std::string& buffer, bool pretty, std::string_view indent) const
    {
        details::StringSerializeHandler ssh(buffer);
        details::JsonSerializer<basic_json, details::StringSerializeHandler>
            serializer(ssh);
        if (pretty)
            serializer.template dump<true>(*this, indent);
        else
            serializer.template dump<false>(*this);
    }

    BASIC_JSON_TEMPLATE
    void BASIC_JSON_TYPE::dump(std::ostream& os, bool pretty, std::string_view indent) const
    {
        details::OStreamSerializeHandler ossh(os);
        details::JsonSerializer<basic_json, details::OStreamSerializeHandler>
            serializer(ossh);
        if (pretty)
            serializer.template dump<true>(*this, indent);
        else
            serializer.template dump<false>(*this);
    }

    BASIC_JSON_TEMPLATE
    template <typename SerializeHandlerT,
        std::enable_if_t<traits::is_json_serialize_handler_v<SerializeHandlerT>, int>>
    void BASIC_JSON_TYPE::dump(SerializeHandlerT& handler, bool pretty, std::string_view indent) const
    {
        details::JsonSerializer<basic_json, SerializeHandlerT> serializer(handler);
        if (pretty)
            serializer.template dump<true>(*this, indent);
        else
            serializer.template dump<false>(*this);
    }

    BASIC_JSON_TEMPLATE
    std::string BASIC_JSON_TYPE::stringify() const
    {
        std::string buffer;
        dump(buffer);
        return buffer;
    }

    BASIC_JSON_TEMPLATE
    std::string BASIC_JSON_TYPE::pretty(std::string_view indent) const
    {
        std::string buffer;
        dump(buffer, true, indent);
        return buffer;
    }

    /*
     * end asserted accessor
     */
}


// ---- end: src/detail/basic_json_impl.hpp ----

// ---- begin: src/jsonpp.hpp ----
/*
jsonpp - A modern, header-only C++ JSON library
Copyright 2025-2026 Mikami (jsonpp project)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */



// ---- end: src/jsonpp.hpp ----

#endif // JSONPP_SINGLE_INCLUDE_JSONPP_HPP
